### PR TITLE
Move CRM and SQL types under a root-level Models namespace

### PR DESCRIPTION
**Pull request by gunndabad**
Consolidates namespaces to give some symmetry to CRM-related types and SQL-related types.

```
DqtApi
  DataStore
    Crm
      Models
    Sql
      Models
```

### CODE REVIEW

**Comment by gunndabad** [comment]
@JonathanWacks This is initial stab at reshuffling namespaces a little in preparation for us putting more stuff into Postgres. Any thoughts on this structure?

**Comment by JonathanWacks** [comment]
Can't we just have:
DqtApi
    Models
         CRM
         SQL

?

**Comment by gunndabad** [comment]
> Can't we just have: DqtApi Models CRM SQL
> 
> ?

Do remove the `DataStore` namespace and have `Crm` + `Sql` at the root?

**Comment by JonathanWacks** [comment]
Sorry, formatting came out lousy there.  
DqtApi
--------Models
----------------CRM
----------------SQL

So DqtApi at top, then Models, then CRM/SQL folders under that.
Is that too simplistic?

**Comment by gunndabad** [comment]
Works for me.

**Comment by JonathanWacks** [comment]
I don't think *all* the CRM stuff should go into Models/CRM though - the stuff I had in DAL was more of a wrapper around CRM, e.g. DataverseAdaptor.  Maybe DAL should also be split into DAL/CRM and DAL/SQL ?

**Comment by JonathanWacks** [comment]
That sounds fine, but do you then want to do DAL folders inside each of CRM/SQL?  So e.g.
DqtApi
-------CRM
------------DAL
-----------------DataverseAdaptor, etc.
------------Models
------------------GeneratedCode, etc.
------SQL
-----------DAL
----------------DbContext
-----------Models
----------------SQLModelStuff 

Or is that too complicated?

**Comment by gunndabad** [comment]
Rebased with structure from https://github.com/DFE-Digital/qualified-teachers-api/pull/43#issuecomment-992635262

**Review by dankmitchell — APPROVED** [review]

**Pull request merged**
